#
# Copyright (C) 2015 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
- name: Find out if user has been added before
  stat: path=/home/vagrant/add-user-{{ uid }}.ldif
  register: add_script

- name: Generate password-hash 
  command: slappasswd -h {SSHA} -s {{ uid }}
  register: hash
  when: add_script.stat.exists == False

- name: Create ldif script to add user {{ uid }}
  template: src={{ ldif_template }}
    dest=/home/vagrant/add-user-{{ uid }}.ldif
  when: add_script.stat.exists == False
    
- name: Execute ldif script
  command: ldapadd -w {{ easy_test_users_ldapadmin_password }} -D cn=ldapadmin,dc=dans,dc=knaw,dc=nl
    -f /home/vagrant/add-user-{{ uid }}.ldif
  when: add_script.stat.exists == False
    