#
# Copyright (C) 2015 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- hosts: "test"
  become: yes
  vars:
    local_test_vm_base_backend_port: 20100
    easy_ldap_dir_ldapadmin_password: "ldapadmin"
    easy_ldap_dir_easyadmin_password: "easyadmin"
    easy_test_users_email: "{{ deployer_email }}"
    easy_test_users_ldapadmin_password: "{{ easy_ldap_dir_ldapadmin_password }}"
  roles:
    - dans.capture-deployer-email
    - dans.local-test-vm-base
    - dans.local-yum-repo
    - dans.easy-ldap-dir
    - dans.easy-test-users

- hosts: "test"
  become: yes
  tasks:
  - name: Create directories
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      mode: "0777"
    with_items:
        - /var/opt/dans.knaw.nl/tmp/easy-sword2
        - /var/opt/dans.knaw.nl/spool/sword2-deposits

  - name: Install package
    yum:
      name: dans.knaw.nl-easy-sword2
      state: latest

  - service:
      name: easy-sword2
      state: started
      enabled: yes
